const interopDefault = r => r.default || r || [];
const styles = {
  "pages/about.vue": () => import('./_nuxt/about-styles.krTUYHIV.mjs').then(interopDefault),
  "pages/index.vue": () => import('./_nuxt/index-styles.bIZfom4t.mjs').then(interopDefault),
  "pages/projects/index.vue": () => import('./_nuxt/index-styles.-wxyolRb.mjs').then(interopDefault),
  "pages/projects/photos.vue": () => import('./_nuxt/photos-styles.wPE_eiQ9.mjs').then(interopDefault),
  "pages/projects/web/ecpm.vue": () => import('./_nuxt/ecpm-styles.4CRD7YNm.mjs').then(interopDefault),
  "pages/projects/index.vue?vue&type=style&index=0&scoped=1c93b942&lang.css": () => import('./_nuxt/index-styles.-wxyolRb.mjs').then(interopDefault),
  "pages/projects/web/jaimeca.vue": () => import('./_nuxt/jaimeca-styles.iRpWxHUH.mjs').then(interopDefault),
  "pages/projects/web/index.vue": () => import('./_nuxt/index-styles.4EE6aGzo.mjs').then(interopDefault),
  "pages/projects/web/karma.vue": () => import('./_nuxt/karma-styles.Hj6QZRNm.mjs').then(interopDefault),
  "pages/projects/web/lilblack.vue": () => import('./_nuxt/lilblack-styles.QrB-2NJ8.mjs').then(interopDefault),
  "pages/projects/web/overlord-fight.vue": () => import('./_nuxt/overlord-fight-styles.sv2OaJX2.mjs').then(interopDefault),
  "pages/projects/web/post-tournage.vue": () => import('./_nuxt/post-tournage-styles.2FBUKnmk.mjs').then(interopDefault),
  "pages/projects/web/index.vue?vue&type=style&index=0&scoped=e6b9cc4f&lang.css": () => import('./_nuxt/index-styles.4EE6aGzo.mjs').then(interopDefault),
  "pages/about.vue?vue&type=style&index=0&scoped=d2166212&lang.css": () => import('./_nuxt/about-styles.krTUYHIV.mjs').then(interopDefault),
  "pages/index.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/index.vue.-vIH0Zv7.mjs').then(interopDefault),
  "pages/index.vue?vue&type=style&index=1&scoped=6fe8f026&lang.css": () => import('./_nuxt/index.vue.VemSWp0R.mjs').then(interopDefault),
  "pages/projects/photos.vue?vue&type=style&index=0&scoped=676f44d2&lang.css": () => import('./_nuxt/photos-styles.wPE_eiQ9.mjs').then(interopDefault),
  "pages/projects/web/ecpm.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/ecpm-styles.4CRD7YNm.mjs').then(interopDefault),
  "pages/projects/web/jaimeca.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/jaimeca-styles.iRpWxHUH.mjs').then(interopDefault),
  "components/cardproject.vue": () => import('./_nuxt/cardproject-styles.CvT9PCKS.mjs').then(interopDefault),
  "pages/projects/web/karma.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/karma-styles.Hj6QZRNm.mjs').then(interopDefault),
  "pages/projects/web/lilblack.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/lilblack-styles.QrB-2NJ8.mjs').then(interopDefault),
  "pages/projects/web/overlord-fight.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/overlord-fight-styles.sv2OaJX2.mjs').then(interopDefault),
  "pages/projects/web/post-tournage.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/post-tournage-styles.2FBUKnmk.mjs').then(interopDefault),
  "components/cardproject.vue?vue&type=style&index=0&scoped=9a818594&lang.css": () => import('./_nuxt/cardproject-styles.CvT9PCKS.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.76vs4_lx.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.vPkMidp2.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=ccd3db62&lang.css": () => import('./_nuxt/error-404-styles.76vs4_lx.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=df79c84d&lang.css": () => import('./_nuxt/error-500-styles.vPkMidp2.mjs').then(interopDefault),
  "components/card.vue": () => import('./_nuxt/card-styles.0NFxCaj6.mjs').then(interopDefault),
  "components/card.vue?vue&type=style&index=0&scoped=51d8adc3&lang.css": () => import('./_nuxt/card-styles.0NFxCaj6.mjs').then(interopDefault),
  "layouts/default.vue": () => import('./_nuxt/default-styles.A85mZqXP.mjs').then(interopDefault),
  "layouts/default.vue?vue&type=style&index=1&lang.css": () => import('./_nuxt/default.vue.ACwQ-p1_.mjs').then(interopDefault),
  "layouts/default.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/default.vue.fT0ghDDC.mjs').then(interopDefault)
};

export { styles as default };
//# sourceMappingURL=styles.mjs.map
